### ISSUE TITLE
Invite to teste the App

### ISSUE THREAD

**Issue by fssantos95** [Looking4Cache/node-red-contrib-remote#1]
Hello. I want to try the app. Couldn't find your e-mail.
Invite me please!

**Comment by Looking4Cache** [comment]
Hi,

the Remote-RED ecosystem is already live. That means that you can download the Apps from the official AppStores (Apple AppStore and Google PlayStore). The necessary Node-RED Nodes are available  inside the pallete for automated installation.

But I will add a contact and a link to my homepage on the Readme.MD..

Best, Thorsten
