### ISSUE TITLE
Remote access is not connecting with network

### ISSUE THREAD

**Issue by syedaminulhaq** [Looking4Cache/node-red-contrib-remote#10]
Hi,
install node-red-contrib-remote from manage pallet and did basic setting but it is not connecting with the network, i have seen on my command prompt that node-red-contrib-remote when i start flows see pic for reference
![nodered1](https://user-images.githubusercontent.com/94774388/142750599-7d3d5c79-68e8-4b56-b8d0-0afdc56699a3.PNG)

**Comment by Looking4Cache** [comment]
Hi,

this looks exactly like a error I fixed in V1.3.2. But I saw, that V1.3.2 was not pushed on the GitHub repro (I don't know if Node-RED installs the nodes from npm or from GitHub...).

Can you check if you installed V1.3.2? If no, please update. If yes, can you please uninstall my nodes and reinstall?

**Comment by syedaminulhaq** [comment]
Do i need to check node red version or any other

**Comment by Looking4Cache** [comment]
I mean the version of the Remote-RED nodes installed on your Node-RED. Thats inside "Manage pallete":

![node-version](https://user-images.githubusercontent.com/2605151/142756744-97af5735-0e30-47c3-a7e6-f4d41ecfaefc.png)

**Comment by syedaminulhaq** [comment]
Hi i have updated remote access node to 1.3.2 but problem is same can u suggest
![nodered3](https://user-images.githubusercontent.com/94774388/142805521-e3714d2e-9ae5-4c59-9ed5-517e3003bf0a.PNG)
![nodered4](https://user-images.githubusercontent.com/94774388/142805528-988e7a3a-37ed-447f-b4c3-5d719fbab30c.PNG)
 how to solve kindly see setting in picture

**Comment by Looking4Cache** [comment]
I just released the node version 1.3.3. Here I changed the method to get the path for package.json. Maybe this works better on your Windows environment.

**Comment by syedaminulhaq** [comment]
how can i update there is no update buton active in manage pallet

**Comment by Looking4Cache** [comment]
The logs looks fine. The "s7 endpoint" error is something other not Remote-RED related.

The most actual Windows Versions have already OpenSSH installed.

**Comment by syedaminulhaq** [comment]
Hi,
Thanks a lot after updating the problem is resolved and  now , i can connect with remote red app, 
now can i connect node red dash board on my mobile with another network
