### ISSUE TITLE
Template with iframe not working

### ISSUE THREAD

**Issue by TadyTheFish** [Looking4Cache/node-red-contrib-remote#13]
Hello 
I'm having some trouble with remote-red not showing iframes. 
I have a few tabs that have the template node inside for embedding.
one tab is is fro music and it show the Mopidy web interface, the other is used for displaying grafana grafs.
It works on my PC browser and my phone but not via remote.
Is there a problem of ports?
Because Mopidy uses 6680 port and grafana uses port 3000?

**Comment by Looking4Cache** [comment]
Hi,

using iFrames will not work with my remote proxy solution. Your dashboard will be loaded through the proxy and then there is a "browser in browser window" that tries to open a local ip, but you are outside your local network.

Maybe you can add two other remote access nodes and try to point on the other two pages. A lot of pages, if they follow some rules of good coding practices (like using relativ paths), can be proxies. For this adjust the IP, port and Base URL to the local pages (out of the sight of the Node-RED server) and add them to the Remote-RED app.

**Comment by TadyTheFish** [comment]
Ok thank you so much for the explanation.
