### ISSUE TITLE
Cannot redirect to NodeRed Dashboard 

### ISSUE THREAD

**Issue by ajaybnl** [Looking4Cache/node-red-contrib-remote#14]
I have set Base Url to "/ui" but the page loads to node-red, and not dashboard.

Please help

**Comment by Looking4Cache** [comment]
Was the config before other, like directly "/" or empty when you generated and scanned the QR code? If yes, the instance have to be removed from the app and you must reconnect with a new QR code.

If not, can you please use the "Mail to support" button inside the config node, so I got the Instance Hash for looking in the logs?
