### ISSUE TITLE
Send jpg in notification?

### ISSUE THREAD

**Issue by daxliniere** [Looking4Cache/node-red-contrib-remote#2]
Hi Thorsten, Remote-RED seems GREAT! I just set it up in about 5 minutes flat.
Would it be possible to pass a jpg image in the notification?

Thanks,
Dax.

**Comment by Looking4Cache** [comment]
I just checked it. To pass a jpg directly in the notification will not be possible, as a notification can have 4kb payload at max. It is possible for me to pass the url of an image in the notification and then download the image when the notification is displayed. But this image as to been served from Node-RED and my node have to store it until it is requested from the device(s). Alternatively I have to upload it to my server and store it there for the device request, but this will be difficult for security and privacy reasons (I think most would use it for camera images). I will put that on my issue tracker for future functions that it will not be forgotten, but I have other functions that will come first.

**Comment by daxliniere** [comment]
Hey Thorsten, thank you for the reply and for looking into it. I appreciate your time.

Is there a way Remote-RED could be run on my own Pi server?
