### ISSUE TITLE
Self-hosted option?

### ISSUE THREAD

**Issue by mobamoba** [Looking4Cache/node-red-contrib-remote#3]
Your app seems really cool but I'd prefer to do it all self-hosted rather than use your servers. Is there a way to make that an option? Thanks.

**Comment by Looking4Cache** [comment]
I have currently no plans to add a self hosting variant. Beside the complex of releasing and supporting the server component, there are some heavy tasks on the certificate generation. So that's to much for me now..

**Comment by mobamoba** [comment]
Okay well can you explain what data is being sent to your server, how long it's held, is it encrypted, stuff like that? I looked around on your site but find anything. Thanks.

**Comment by Looking4Cache** [comment]
In a short version the informations what is stored on my servers is written down in the privacy policy. Here are more detailed informations.

For each instance a instanceHash will be calculated. This is just a random hash which does not contain any personal informations of you. With this instanceHash all communications over my server (Node-RED nodes <> Mobile apps) will happen. For this the instanceHash and a generic server-side generated password (which is needed by the apps to initially connect) will be stored on the server. At the moment this two informations are stored without deletion date.

For future releases I plan to add a "last seen online" date and a "last version used" to delete old, unused instances.

For notifications the apps sends Google Cloud Messaging device token to my server if you decide to activate notifications. This device token is also stored on my server without a deletion date.

If a notification is send it will be stored on a quere inside a database and send as soon as possible (normally within the next seconds). If something errors here (like connection to the Google service is down), it will be stored until it is send later (never happed until now). The notification content will be deleted after it was send.

Also there are logs on my servers containing stuff like https requests, reconnects and notifications. These logs includes the instanceHash for support and debug work. IP addresses are only stored if strange thinks like "wrong passwords" or multiple requests are happened to ban this IPs. The logs will be deleted within 30 days.

If someone want, I will delete all informations liked to a instanceHash. This is guaranteed by the GDPR / DSGVO.


At all I prefer to store as less as possible. My servers are mostly used for proxying requests between your phone and your Node-RED, not for collecting data.

**Comment by Looking4Cache** [comment]
My server or I did not know what you did. Depending on the log level I run my server I only see events like
- Requests for new SSH connections
- New Instance creations
- Notification sends
- Proxy usage (App opens something on your Node-RED Instance)
- ...

By the "Procy usage", I only see that there is a connection including the URL. And also only if I activated a high log level for debugging. But at all I see no content of the connection. The content of the connection is directly passed by a proxy function between your phone and your Node-RED server.

**Comment by mobamoba** [comment]
Thanks. I'm asking in part because my NR instance is behind a reverse proxy and protected by basic authentication which places the username and password in the URL, i.e. https://user:password@yourdashboardui.com. So will your server be able to see that?

**Comment by Looking4Cache** [comment]
Thats a very special configuration where I don't know if it works. Just try it.. The InApp purchases are only necessary after several successful connects.

Basic Auth from Node-RED itself works inside my apps. So you can try if it also works with your reverse proxy.

When it works, then I assume that it use some wired routing. When you enter the "public" url inside the serving host config field, then the remote access node on your Node-RED computer serves a connection to your reverse proxy which proxies it back to your local Node-RED computer. So I think it will go two times through the internet. Maybe more than needed with that reverse proxy..

**Comment by mobamoba** [comment]
My concern is that, because my username and password are in the URL, they'll be stored in plaintext on your server.

**Comment by Looking4Cache** [comment]
OK, I understand your concern.

The field 'Serving Host' will not be transferred to my server. This field will only be available on your local Node-RED installation and in the apps you connect. The apps get it though the QR Code, not through my server.

Here is the background: Your local remote access node asks every time when it want to connect for a port on my server. Then a ssh tunnel between your local computer and my server will be esablished from your local computer. The target of this ssh tunnel is the field 'Serving Host'. On my server, when a app proxy requests arrives, it just looks for the connected port and redirects the request to your port. So my server did not need the url.

When your local computer requests a port for connecting, it sends the instanceHash, instanceAuth, Protocol, Serving Port, and Base URL which is held in a In-Memory list.


But I think you should not need to enter your username and password in the URL. Just enter the URL without Basic Auth informations. When your reverse proxy uses normal Basic Auth and the app connects over my proxy to the url, the reverse proxy server should start a authentication challenge. Then my apps should display a username / password prompt. Here you can enter your credentials. If you choose to store them for later use, they will be stored encrypted on your mobile (using the default technique of the operation system like keychain on iOS).

**Comment by mobamoba** [comment]
I see. I didn't realize your app would be passing along the authentication requests and thought I'd need to include it in the URL.
