### ISSUE TITLE
Using a global replace on the path is dangerous

### ISSUE THREAD

**Issue by hardillb** [Looking4Cache/node-red-contrib-remote#8]
https://github.com/Looking4Cache/node-red-contrib-remote/blob/main/nodes/remote-commons.js#L22 assumes there will only ever be one instance of `/nodes` in the path. This is not a safe assumption.

You should use `path.join(__dirname. "../package.json")` to locate the required file.

Raise as the most likely cause of https://stackoverflow.com/questions/69859678/error-configurating-remote-node-red-module

**Comment by Looking4Cache** [comment]
Thanks for the help! I just changed it and released V1.3.2.
