### ISSUE TITLE
Direct Connection for local  use

### ISSUE THREAD

**Issue by tkirchm** [Looking4Cache/node-red-contrib-remote#9]
Hi,

i like your work and I would like to use it. The only downside is slow loading.

As this is the problem of the proxy can't u let us connect direct to nodered via local IP adress (http). 
No certificate or encryption needed as this can only be used inside my own network or when I'm connected via VPN.
Just add local IP to "Standort Server".
In my case I'm connected permanent via VPN and so everything would work fine.

**Comment by Looking4Cache** [comment]
Hi,

if the IP address entered in the field "Serving Host" is reachable, the app connects your dashboard directly. Only if it is not reachable, it connects over my proxy servers.

So if you enter a IP that is reachable over your VPN, it should load fast(er).

The "Standort Server" is for more than just the dashboard connection. It is also used for notifications and remote actions (iOS Shortcut app / Android Widget).

**Comment by tkirchm** [comment]
Still very slow.

Now I just get the payment info and that means I can't test it any more.
